import Foundation
import SessionHealthCore

let suite = TestSuite()
let load = ThresholdConfigLoader.loadBundled()

guard load.problems.isEmpty else {
    print("the bundled threshold config did not load cleanly:")
    for problem in load.problems { print("  \(problem)") }
    exit(1)
}

print("Threshold config")
runThresholdConfigTests(suite, config: load.config)
print("")
print("Budget rules")
runBudgetRulesTests(suite, config: load.config)
print("")
print("Alert memory")
runAlertMemoryTests(suite, config: load.config)
print("")
print("Alert dispatch")
runAlertDispatchTests(suite, config: load.config)
print("")
print("Notification text")
runNotificationTextTests(suite, config: load.config)
print("")
print("Session activity")
runSessionActivityTests(suite, config: load.config)
print("")
print("Claude status line")
runClaudeStatusTests(suite, config: load.config)
runClaudeSourceJoinTests(suite, config: load.config)
print("")
print("Claude transcripts")
runClaudeTranscriptTests(suite, config: load.config)
print("")
print("What the reader remembers between passes")
runTranscriptMemoryTests(suite, config: load.config)
runSourceMemoryTests(suite, config: load.config)
print("")
print("Waiting on an answer")
runWaitingStateTests(suite, config: load.config)
runCodexWaitingStateTests(suite, config: load.config)
print("")
print("Waiting on the person")
runAskingStateTests(suite, config: load.config)
print("")
print("Claude subagents")
runClaudeAgentTests(suite, config: load.config)
print("")
print("Codex rollouts")
runCodexRolloutTests(suite)
print("")
print("Codex sessions")
runCodexSessionTests(suite, config: load.config)
print("")
print("Large transcripts")
runLargeTranscriptTests(suite, config: load.config)
print("")
print("Watching the sources")
runSourceWatcherTests(suite)
print("")
print("Setup and the first run")
runSetupTests(suite, config: load.config)
print("")
print("Taking the status line slot")
runStatusLineSlotTests(suite)
print("")
print("The app as the status line command")
runStatusLineModeTests(suite)
runStatusLineTextTests(suite)
runStatusLineBinaryTests(suite)
print("")
print("Staying offline")
runOfflineTests(suite)

suite.finish(section: "SessionHealthTests")
